baseURL: 'https://www.blimbing.web.id/'
title: 'Desa Wisata Blimbing'
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
  author: KKN PPM UGM 2024 - Abdi Ing Panjalu
  authorimage: ../assets/images/global/author.webp
  og_image: /images/tailbliss-cover.png
  moto: "Blimbing"
  description: "Desa Blimbing adalah Desa Blimbing di Kecamatan Mojo, Kediri, memiliki populasi sekitar 4.094 jiwa yang tersebar di empat dusun. Selain populasi yang besar, desa ini juga dikenal dengan perkebunan durian yang subur, menghasilkan durian berkualitas tinggi yang menjadi daya tarik wisata lokal. Oleh karena itu, Desa ini memiliki destinasi wisata yang bernama Taman Bukit Duraemont, yang merupakan kependekan dari Durian Asli Enak Montong Tempatan. Selain durian, petani di desa ini juga menanam cengkeh yang menjadi sumber penghasilan utama, meskipun mereka menghadapi tantangan seperti fluktuasi harga dan serangan hama. Dukungan dari pemerintah dan inovasi dalam pertanian membantu petani mengoptimalkan hasil panen dan menjaga tradisi pertanian di desa ini."
  disable_theme_toggle: true
  disable_stay_uptodate: true

  decor:
    image: "images/pages/sidedecor.png"
  hero:
    image: "images/pages/hero.jpeg"
  p4:
    heading: "Artikel dan Blog"
    content:
      - text: "Berikut adalah artikel dan blog yang telah disusun oleh warga Desa Blimbing"
  p5:
    heading: "Stay Up to Date"
    content:
      - text: "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque."
    action: "#"
    label: "Email address"
    placeholder: "Enter your email"
    button: "Notify me"

  social_media:
    github:
      enabled: false
      url: 'https://github.com/dundorma'
    facebook:
      enabled: false
      url: 'https://facebook.com/'
    instagram:
      enabled: false
      url: 'https://instagram.com/dundorma'
    twitter:
      enabled: false
      url: 'https://twitter.com/catwavess'
    

menu:
  main:
    - identifier: artikel
      name: Artikel
      url: /posts/
      weight: 10
    - identifier: profil
      name: Profil
      url: /about/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
